import crypto from 'node:crypto';
import { memoryStore } from './sr2-store.mjs';
import { createSr2Service } from '../../backend/sr2/service.js';
import { extendSr2Issuance } from '../../backend/sr2/issuance.js';
import { createSr2Adapters, sr2VerifyCredential } from '../../backend/sr2/adapters.js';

export const alpha='11111111-1111-4111-8111-111111111111',beta='22222222-2222-4222-8222-222222222222';
export function configuration(identifier='Employee'){return {identifier,name:identifier,description:'Employee credential',profile:'oid4vci-1.0',format:'jwt_vc_json',credentialTypes:['VerifiableCredential',identifier+'Credential'],claims:[{name:'name',type:'string',required:true}],flowId:null,connectorId:null,signingMode:'internal-signing',keyRef:'tenant-key',statusProfile:'status-list',eligibility:{subjects:[],roles:['principal']},ratePerMinute:10,blockReissuance:true};}
export const flow=()=>({name:'Consent journey',steps:[{id:'consent',type:'consent',title:'Consent',text:'Information',fields:[]},{id:'offer',type:'offer',title:'Offer',text:'Result',fields:[]}]});
export const connector=()=>({configurationIds:null,name:'Participant',endpoint:'https://participant.example.com/grpc',serverName:'participant.example.com',protocolVersion:'participant-v1',tlsSecret:{name:'participant-client'},trustSecret:{name:'participant-trust'},jwtIssuer:'https://identity.example.com',jwtAudience:'participant-data',jwtScopes:['credential:issue'],signingModes:['internal-signing','participant-signed'],timeoutMs:5000,attempts:1,ratePerMinute:10});
export function fixture(useFake=true){
 const tenants=[alpha,beta].map((id,i)=>({tenant_id:id,primary_domain:(i?'beta':'alpha')+'-pci.example.com',state:'active',tenant_slug:i?'beta':'alpha',owner_uid:crypto.randomUUID()}));
 const members=tenants.flatMap(t=>['admin','issuer','principal'].map(subject=>({tenantId:t.tenant_id,subject,roles:subject==='admin'?['participant_tenant_admin','principal']:['principal']})));
 const store=memoryStore(tenants,members),calls=[],privateClaim=crypto.randomUUID();let clock=1800748800000;
 const privateKeys=tenants.map(()=>crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'}));
 function sign({tenant,configuration,principal,status,metadata}){const pair=privateKeys[tenant.tenant_id===alpha?0:1],head={alg:'ES256',kid:'tenant-key',typ:'JWT'},claims={jti:'urn:uuid:'+crypto.randomUUID(),iss:metadata.did,sub:principal.subject,iat:Math.floor(clock/1000),exp:Math.floor(clock/1000)+3600,vc:{issuer:metadata.did,type:configuration.credentialTypes,credentialSubject:{id:principal.subject,name:privateClaim},credentialStatus:status.entry}};const body=[head,claims].map(x=>Buffer.from(JSON.stringify(x)).toString('base64url')).join('.');return body+'.'+crypto.sign('sha256',Buffer.from(body),{key:pair.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64url');}
 const adapters=useFake?{capabilities:()=>({ready:true,testDouble:true}),assertReady:async()=>{},publishMetadata:async()=>{calls.push('publish');},createOffer:async c=>{calls.push('offer');return {tenantId:c.r.tenantId,requestId:c.r.id,configurationId:c.r.configurationId,offerUrl:'openid-credential-offer://?request='+c.r.id};},participantIdentity:async()=>{calls.push('identity');},notifyParticipant:async c=>{calls.push('notify');return {accepted:true,requestId:c.r.id};},getParticipantData:async c=>{calls.push('data');return {requestId:c.r.id,...(c.configuration.signingMode==='participant-signed'?{signedCredential:sign(c)}:{unsignedData:{subject:c.principal.subject,claims:{name:privateClaim}}})};},allocateStatus:async c=>{calls.push('status');return {tenantId:c.r.tenantId,configurationId:c.r.configurationId,requestId:c.r.id,handle:c.r.id,entry:{id:'https://'+c.tenant.primary_domain+'/status#'+parseInt(c.r.id.replaceAll('-','').slice(0,12),16),type:'BitstringStatusListEntry',statusPurpose:'revocation',statusListIndex:String(parseInt(c.r.id.replaceAll('-','').slice(0,12),16)),statusListCredential:'https://'+c.tenant.primary_domain+'/status'}};},sign:async c=>{calls.push('sign');return sign(c);},verifySigned:async c=>{calls.push('verify');const pair=privateKeys[c.r.tenantId===alpha?0:1];return sr2VerifyCredential(c.credential,c.configuration,{issuer:c.metadata.did,subject:c.principal.subject,kid:'tenant-key',status:c.status.entry},{keys:[{...pair.publicKey.export({format:'jwk'}),kid:'tenant-key',alg:'ES256',use:'sig'}]},clock);},revokeStatus:async c=>{calls.push('revoke');return {revoked:true,tenantId:c.tenantId,requestId:c.requestId,handle:c.status.handle};}}:createSr2Adapters();
 const api=extendSr2Issuance(createSr2Service({store,adapters,pepper:crypto.randomBytes(32),now:()=>clock,allowedHosts:['participant.example.com'],issuerUrl:t=>'https://'+t.primary_domain,assetUrl:(t,id)=>'https://'+t.primary_domain+'/api/v1/public/assets/'+id}));
 const principal=(subject='admin',id=alpha)=>({subject,tenantId:id,host:tenants.find(t=>t.tenant_id===id).primary_domain,roles:subject==='admin'?['participant_tenant_admin','principal']:['principal']});
 async function publish(kind,item,p=principal()){return (await api.resource(p,kind,'publish',item.id,{},item.version)).item;}
 async function prepared(identifier='Employee',mode='internal-signing',id=alpha){const p=principal('admin',id),origin='https://'+p.host;
  if(!(await api.resource(p,'metadata','get',id)).item)await publish('metadata',(await api.resource(p,'metadata','create',null,{data:{profile:'oid4vci-1.0',issuer:origin,authorizationServers:['https://identity.example.com'],did:'did:web:'+p.host,jwksUrl:origin+'/jwks',displayName:'Tenant'}})).item,p);
  const c=await publish('connector',(await api.resource(p,'connector','create',null,{data:connector()})).item,p);
  let config=(await api.resource(p,'configuration','create',null,{data:{...configuration(identifier),signingMode:mode,connectorId:c.id}})).item;
  const f=await publish('flow',(await api.resource(p,'flow','create',null,{configurationId:config.id,data:flow()})).item,p);
  config=(await api.resource(p,'configuration','update',config.id,{data:{...config.draft,flowId:f.id}},config.version)).item;config=await publish('configuration',config,p);return {config,flow:f,connector:c};
 }
 async function offered(config,p=principal('principal')){let r=await api.start(p,config.id,crypto.randomUUID());r=await api.advance(p,r.request.requestId,{step:0,consent:true});await api.offer(p,r.request.requestId);return r.request.requestId;}
 return {api,store,adapters,calls,privateClaim,principal,publish,prepared,offered,clock:()=>clock,advanceClock:ms=>{clock+=ms;}};
}
