import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';
import {pciQrMatrix,pciQrImage} from '../../../src/qr.js';
const reference=JSON.parse(fs.readFileSync('test/support/qr-reference.json'));
test('all forty QR versions match independently generated byte-mode L matrices',()=>{
 for(const c of reference.cases){const m=pciQrMatrix('A'.repeat(c.byteLength),0);assert.equal(m.length,c.version*4+17);assert.equal(crypto.createHash('sha256').update(m.flat().map(b=>b?'1':'0').join('')).digest('hex'),c.sha256,'version '+c.version);}
});
test('offer QR uses bounded SVG path data and a four-module quiet border',()=>{
 const image=pciQrImage('openid-credential-offer://?request=example');assert.ok(image.size>21);assert.match(image.path,/^[M0-9 hvz-]+$/);assert.throws(()=>pciQrMatrix('A'.repeat(4000)));
});
