import { mkdir, readFile, writeFile, copyFile } from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";

const root = process.cwd();
const outDir = path.join(root, ".build", "ui");
const releaseVersion = (await readFile(path.join(root, "VERSION"), "utf8")).trim();
const sources = [
  "shared/public-url.js",
  "src/config/runtime.js",
  "src/utils/pkce.js",
  "src/services/api.js",
  "src/services/auth.js",
  "src/state/store.js",
  "src/qr-tables.js",
  "src/qr.js",
  "src/sr2.js",
  "src/main.js",
];
function transform(source) {
  return source
    .replace(/^import\s+.*?;\s*$/gm, "")
    .replace(/^export\s+(?=(?:async\s+)?function|const|let|var|class)/gm, "");
}
const chunks = [];
for (const file of sources) chunks.push(`// ---- ${file} ----\n${transform(await readFile(file, "utf8"))}`);
let bundle = `/* Generated by tools/build-ui.mjs. Vue is a vendored pinned browser global. */\n(() => {\n"use strict";\nconst { createApp, computed, onMounted, ref, reactive } = Vue;\n${chunks.join("\n\n")}\n})();\n`;
bundle = bundle.replaceAll("__FAP_PCI_VERSION__", releaseVersion);
if (bundle.includes("__FAP_PCI_VERSION__")) throw new Error("unresolved release version placeholder in UI bundle");
await mkdir(outDir, { recursive: true });
await writeFile(path.join(outDir, "index.js"), bundle);
await copyFile(path.join(root, "src", "index.html"), path.join(outDir, "index.html"));
await copyFile(path.join(root, "src", "styles.css"), path.join(outDir, "index.css"));
const vue = await readFile(path.join(root,'vendor','vue.global.prod.js'));
const provenance = JSON.parse(await readFile(path.join(root,'vendor','vue-provenance.json'),'utf8'));
if (createHash('sha256').update(vue).digest('hex') !== provenance.sha256) throw new Error('Vendored Vue digest mismatch');
await writeFile(path.join(outDir,'vue.global.prod.js'),vue);
console.log(`[build-ui] wrote canonical UI assets to ${outDir}`);

await writeFile(path.join(outDir,'THIRD_PARTY_LICENSES.txt'),(await readFile(path.join(root,'vendor','vue-LICENSE.txt'),'utf8'))+'\n'+(await readFile(path.join(root,'vendor','qr-tables-LICENSE.txt'),'utf8')));
