// Single Vue/uibuilder application: all authority is rechecked by the HTTP API.
const Sr2Console = {
  props:['tenant','session'],
  setup(props) {
    const query=ref(''),configState=ref('all'),loaded=ref(false);
    const tab=ref('request'),notice=ref(''),error=ref(''),busy=ref(false),cap=ref({}),configs=ref([]),flows=ref([]),connectors=ref([]),assets=ref([]),assignments=ref([]),members=ref([]),eligible=ref([]),history=ref([]),versions=ref([]),publication=ref(null);
    const selected=ref(null),selectedFlow=ref(null),configForm=ref(null),flowForm=ref(null),preview=ref(null),metadata=ref(null),branding=ref(null),connector=ref(null),settings=ref(null);
    const metadataForm=ref({profile:'oid4vci-1.0',issuer:window.location.origin+runtime.basePath,authorizationServers:[],did:'',jwksUrl:window.location.origin+runtime.basePath+'/.well-known/jwks.json',displayName:props.tenant.organizationName});
    const authServers=ref(''),brandingForm=ref({title:props.tenant.organizationName,description:'',accent:'#173c67',logoAssetId:null});
    const connectorForm=ref({name:'',endpoint:'',serverName:'',protocolVersion:'participant-v1',tlsSecret:{name:''},trustSecret:{name:''},jwtIssuer:'',jwtAudience:'',jwtScopes:['credential:issue'],signingModes:['internal-signing'],timeoutMs:5000,attempts:1,ratePerMinute:10,circuitFailureThreshold:3,circuitCooldownMs:30000,configurationIds:[]});
    const settingsForm=ref({ratePerMinute:30,maxConcurrent:2}),grant=ref({subject:'',configurationIds:null}),grantConfig=ref(''),search=ref({credentialId:'',requestId:'',subjectHash:'',type:'',cursor:'',from:'',to:''}),nextCursor=ref(null),historyConfig=ref(''),restoreVersion=ref('');
    const journey=ref(null),answers=ref({}),consent=ref(false),offer=ref(null),uploadRole=ref('logoAssetId'),uploadScope=ref('configuration');
    const qr=computed(()=>{if(!offer.value)return null;try{return pciQrImage(offer.value.offerUrl);}catch{return null;}});
    const currentStep=computed(()=>journey.value?.flow?.steps[journey.value.request.step]);
    const sections=computed(()=>[
      {id:'request',label:'Request credential',icon:'M5 4h14v16H5z M8 8h8 M8 12h5 M8 16h3',description:'Choose a credential and follow your organization’s request journey.'},
      ...(cap.value.issuer?[
        {id:'configurations',label:'Configurations',icon:'M3 6h7l2 3h9v11H3z',description:'Define credentials, review drafts, and manage published versions.'},
        {id:'journeys',label:'Journeys',icon:'M5 5h5v5H5z M14 14h5v5h-5z M8 10v7h6',description:'Build the steps your members follow to request a credential.'},
        {id:'history',label:'Issuance history',icon:'M4 8V3 M4 8h5 M4 8a8 8 0 1 1-1 7 M12 7v5l3 2',description:'Find credential records, inspect status, and manage revocation.'}]:[]),
      ...(cap.value.tenantAdmin?[
        {id:'tenant',label:'Tenant settings',icon:'M12 3v4 M12 17v4 M3 12h4 M17 12h4 M7 7l-3-3 M17 17l3 3 M7 17l-3 3 M17 7l3-3 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',description:'Manage issuer identity, organization branding, and issuance limits.'},
        {id:'connectors',label:'Connectors',icon:'M9 3v5 M15 3v5 M6 8h12v4a6 6 0 0 1-12 0z M12 18v3',description:'Connect participant services and approve which configurations can use them.'},
        {id:'delegation',label:'Access & members',icon:'M15 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M5 21v-3a7 7 0 0 1 14 0v3',description:'Invite members and delegate issuer administration.'}]:[])
    ]);
    const section=computed(()=>sections.value.find(x=>x.id===tab.value) || sections.value[0]);
    const filteredConfigs=computed(()=>configs.value.filter(c=>(configState.value==='all'||c.state===configState.value) && (c.draft.name+' '+c.draft.identifier).toLowerCase().includes(query.value.toLowerCase())));
    const availableConnectors=computed(()=>connectors.value.filter(c=>c.state!=='archived' && (c.draft.configurationIds===null || (c.draft.configurationIds || []).includes(selected.value?.id))));
    function navigate(id){tab.value=id;preview.value=null;error.value='';notice.value='';}
    const base=()=>`/api/v1/tenants/${encodeURIComponent(props.tenant.tenantId)}`;
    async function call(path,method='GET',data,version,extra={}) {return request(base()+path,{method,headers:{...(version?{'if-match':`"${version}"`}:{}),...extra},...(method!=='GET'?{body:JSON.stringify(data || {})}:{})});}
    async function run(fn){busy.value=true;error.value='';notice.value='';try{await fn();}catch(e){error.value=e.message;}finally{busy.value=false;}}
    const clone=value=>JSON.parse(JSON.stringify(value));
    async function refresh(){await run(async()=>{
      cap.value=await call('/issuer-capabilities');if(!loaded.value){tab.value=cap.value.issuer?'configurations':'request';loaded.value=true;}if(!sections.value.some(s=>s.id===tab.value))tab.value='request';connectors.value=cap.value.connectors || [];eligible.value=(await call('/eligible-configurations')).items;
      if(cap.value.issuer){configs.value=(await call('/credential-configurations')).items;flows.value=(await call('/flows')).items;assets.value=(await call('/assets')).items;}
      if(cap.value.tenantAdmin){connectors.value=(await call('/participant-connectors')).items;members.value=(await api.tenantMembers(props.tenant.tenantId)).items;assignments.value=(await call('/administrators')).items;
        metadata.value=(await call('/issuer-metadata')).item;if(metadata.value){metadataForm.value=clone(metadata.value.draft);authServers.value=metadataForm.value.authorizationServers.join(', ');}
        branding.value=(await call('/branding')).item;if(branding.value)brandingForm.value=clone(branding.value.draft);
        settings.value=(await call('/issuer-settings')).item;if(settings.value)settingsForm.value=clone(settings.value.draft);
        publication.value=await call('/publication');}
    });}
    function newConfig(){selected.value=null;versions.value=[];configForm.value={identifier:'',name:'',description:'',profile:'oid4vci-1.0',format:'jwt_vc_json',credentialTypes:['VerifiableCredential','EmployeeCredential'],vct:null,claims:[{name:'name',type:'string',required:true}],logoAssetId:null,backgroundAssetId:null,flowId:null,connectorId:null,signingMode:'internal-signing',keyRef:'',statusProfile:'status-list',eligibility:{subjects:[],roles:['principal']},ratePerMinute:10,blockReissuance:true};}
    async function editConfig(item){await run(async()=>{const r=await call('/credential-configurations/'+item.id);selected.value=r.item;configForm.value=clone(r.item.draft);versions.value=r.versions;preview.value=null;});}
    async function saveConfig(){await run(async()=>{const r=await call('/credential-configurations'+(selected.value?'/'+selected.value.id:''),selected.value?'PATCH':'POST',{data:configForm.value},selected.value?.version);selected.value=r.item;configForm.value=clone(r.item.draft);configs.value=(await call('/credential-configurations')).items;notice.value='Draft saved. Publish when ready.';});}
    async function configAction(action){if(!selected.value)return;if(action==='archive'&&!window.confirm('Archive this configuration and stop new requests?'))return;await run(async()=>{const r=await call('/credential-configurations/'+selected.value.id+(action==='archive'?'':'/'+action),action==='archive'?'DELETE':'POST',{},selected.value.version);if(r.item){selected.value=r.item;configForm.value=clone(r.item.draft);}preview.value=r.preview || null;notice.value=action==='validate'?'Local validation passed. External integration still requires its verified contracts.':'Configuration '+action+' completed.';configs.value=(await call('/credential-configurations')).items;});}
    function newFlow(){selectedFlow.value=null;flowForm.value={configurationId:selected.value?.id || configs.value[0]?.id || '',data:{name:'Credential journey',steps:[{id:'intro',type:'information',title:'Your credential',text:'Review the information before requesting.',fields:[]},{id:'consent',type:'consent',title:'Privacy and consent',text:'Your participant data is processed transiently for issuance.',fields:[]},{id:'offer',type:'offer',title:'Receive your credential',text:'Open the credential offer in a compatible wallet.',fields:[]}]}};}
    async function editFlow(item){await run(async()=>{const r=await call('/flows/'+item.id);selectedFlow.value=r.item;flowForm.value={configurationId:r.item.configurationId,data:clone(r.item.draft)};versions.value=r.versions;});}
    function moveStep(index,delta){const steps=flowForm.value.data.steps,target=index+delta;if(target<0||target>=steps.length)return;[steps[index],steps[target]]=[steps[target],steps[index]];}
    function addStep(){const list=flowForm.value.data.steps;list.splice(list.length-1,0,{id:'step'+crypto.randomUUID().slice(0,8),type:'information',title:'New step',text:'',fields:[]});}
    async function flowAction(action){if(action==='save')return run(async()=>{const r=await call('/flows'+(selectedFlow.value?'/'+selectedFlow.value.id:''),selectedFlow.value?'PATCH':'POST',flowForm.value,selectedFlow.value?.version);selectedFlow.value=r.item;flows.value=(await call('/flows')).items;notice.value='Journey draft saved.';});if(!selectedFlow.value)return;await run(async()=>{const r=await call('/flows/'+selectedFlow.value.id+'/'+action,'POST',action==='rollback'?{version:Number(restoreVersion.value)}:{},selectedFlow.value.version);if(r.item){selectedFlow.value=r.item;flowForm.value={configurationId:r.item.configurationId,data:clone(r.item.draft)};}preview.value=r.preview || null;flows.value=(await call('/flows')).items;notice.value=action==='rollback'?'Version restored as a new draft. Publish to activate.':'Journey '+action+' completed.';});}
    async function saveSingleton(kind,item,form,publish=false){await run(async()=>{const r=await call('/'+kind,item?'PUT':'POST',{data:form},item?.version);let saved=r.item;if(publish)saved=(await call('/'+kind+'/publish','POST',{},saved.version)).item;if(kind==='issuer-metadata')metadata.value=saved;if(kind==='branding'){branding.value=saved;props.tenant.branding=clone(saved.draft);}if(kind==='issuer-settings')settings.value=saved;notice.value=publish?'Saved and activated locally.':'Settings saved.';});}
    async function saveMetadata(){metadataForm.value.authorizationServers=authServers.value.split(',').map(x=>x.trim()).filter(Boolean);await saveSingleton('issuer-metadata',metadata.value,metadataForm.value,true);}
    async function saveConnector(){await run(async()=>{let r=await call('/participant-connectors'+(connector.value?'/'+connector.value.id:''),connector.value?'PATCH':'POST',{data:connectorForm.value},connector.value?.version);r=await call('/participant-connectors/'+r.item.id+'/publish','POST',{},r.item.version);connector.value=r.item;connectors.value=(await call('/participant-connectors')).items;notice.value='Connector saved. Transport activation requires the verified protocol adapter.';});}
    const emptyConnector=clone(connectorForm.value);
    function newConnector(){connector.value=null;connectorForm.value=clone(emptyConnector);}
    function editConnector(c){connector.value=c;connectorForm.value={...clone(c.draft),configurationIds:c.draft.configurationIds ?? (Object.hasOwn(c.draft,'configurationIds')?null:[])};}
    async function assign(){await run(async()=>{await call('/administrators','POST',{subject:grant.value.subject,configurationIds:grantConfig.value?[grantConfig.value]:null});assignments.value=(await call('/administrators')).items;notice.value='Issuer capability assigned.';});}
    async function revokeAssignment(a){if(!window.confirm('Revoke this issuer assignment?'))return;await run(async()=>{await call('/administrators/'+a.id,'DELETE');assignments.value=(await call('/administrators')).items;notice.value='Assignment revoked immediately.';});}
    async function upload(event){const file=event.target.files?.[0];if(!file)return;await run(async()=>{if(file.size>1048576)throw new Error('Select a PNG up to 1 MiB.');const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(const b of bytes)raw+=String.fromCharCode(b);const configurationId=uploadScope.value==='tenant'?null:selected.value?.id;if(uploadScope.value==='configuration'&&!configurationId)throw new Error('Save and select a configuration first.');const r=await call('/assets','POST',{configurationId,data:{mediaType:'image/png',base64:btoa(raw)}});assets.value=(await call('/assets')).items;if(configurationId)configForm.value[uploadRole.value]=r.item.id;else brandingForm.value.logoAssetId=r.item.id;notice.value='PNG decoded and re-encoded. Save and publish to expose it.';});event.target.value='';}
    async function archiveAsset(a){if(!window.confirm('Archive this unpublished image?'))return;await run(async()=>{await call('/assets/'+a.id,'DELETE',{},a.version);assets.value=(await call('/assets')).items;notice.value='Image archived.';});}
    async function restoreConfig(){if(!selected.value)return;await run(async()=>{const r=await call('/credential-configurations/'+selected.value.id+'/rollback','POST',{version:Number(restoreVersion.value)},selected.value.version);selected.value=r.item;configForm.value=clone(r.item.draft);notice.value='Version restored as a draft. Publish to activate.';});}
    async function loadHistory(append=false){await run(async()=>{if(!historyConfig.value)return;const q=new URLSearchParams();for(const [k,v]of Object.entries(search.value))if(v)q.set(k,['from','to'].includes(k)?new Date(v).toISOString():v);const r=await call('/credential-configurations/'+historyConfig.value+'/history?'+q);history.value=append?[...history.value,...r.items]:r.items;nextCursor.value=r.nextCursor;});}
    async function revoke(requestId){if(!window.confirm('Revoke this credential through its status provider? This cannot be undone.'))return;await run(async()=>{await call('/credential-configurations/'+historyConfig.value+'/revocations','POST',{requestId,confirmed:true});notice.value='Status provider confirmed revocation.';});await loadHistory();}
    async function start(id){await run(async()=>{offer.value=null;journey.value=await call('/issuance-requests','POST',{configurationId:id},null,{'idempotency-key':crypto.randomUUID()});answers.value={};consent.value=false;});}
    async function next(){await run(async()=>{journey.value=await call('/issuance-requests/'+journey.value.request.requestId+'/advance','POST',{step:journey.value.request.step,consent:consent.value,values:answers.value});answers.value={};consent.value=false;});}
    async function prepareOffer(){await run(async()=>{offer.value=await call('/issuance-requests/'+journey.value.request.requestId+'/offer','POST');});}
    async function publishMetadata(){await run(async()=>{await call('/publication','POST');notice.value='Upstream metadata publication confirmed.';});publication.value=await call('/publication').catch(()=>publication.value);}
    async function lifecycle(state){const confirmation=window.prompt('Enter the tenant slug to confirm '+state+':');if(confirmation===null)return;await run(async()=>{await call('/lifecycle','POST',{state,confirmation});window.location.reload();});}
    onMounted(refresh);
    return {query,configState,sections,section,filteredConfigs,availableConnectors,navigate,tab,notice,error,busy,cap,configs,flows,connectors,assets,assignments,members,eligible,history,versions,publication,selected,selectedFlow,configForm,flowForm,preview,metadata,branding,connector,settings,metadataForm,authServers,brandingForm,connectorForm,settingsForm,grant,grantConfig,search,nextCursor,historyConfig,restoreVersion,journey,answers,consent,offer,qr,currentStep,uploadRole,uploadScope,refresh,newConfig,editConfig,saveConfig,configAction,newFlow,editFlow,moveStep,addStep,flowAction,saveSingleton,saveMetadata,saveConnector,editConnector,newConnector,assign,revokeAssignment,upload,archiveAsset,restoreConfig,loadHistory,revoke,start,next,prepareOffer,publishMetadata,lifecycle};
  },
  template:`<section class="sr2-console" aria-label="Credential issuance workspace">
    <aside class="workspace-sidebar">
      <div class="workspace-brand"><span class="workspace-monogram">PCI</span><div><strong>Credential issuance</strong><small>FACIS Application Platform</small></div></div>
      <div class="workspace-tenant"><span class="nav-caption">ORGANIZATION</span><strong>{{tenant.branding?.title || tenant.organizationName}}</strong><small>{{tenant.primaryDomain}}</small></div>
      <nav class="sr2-tabs" aria-label="Workspace sections"><button v-for="item in sections" :key="item.id" @click="navigate(item.id)" :aria-current="tab===item.id?'page':undefined" :aria-pressed="tab===item.id"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path :d="item.icon"/></svg>{{item.label}}</button></nav>
      <div class="workspace-account"><span class="account-avatar" aria-hidden="true">{{(session.displayName || session.username || session.subject || 'U').slice(0,1).toUpperCase()}}</span><div><strong>{{session.displayName || session.username || session.subject}}</strong><small>{{cap.tenantAdmin?'Tenant administrator':cap.issuer?'Issuer administrator':'Member'}}</small></div></div>
    </aside>
    <div class="workspace-main">
    <header class="workspace-header"><div><span class="workspace-breadcrumb">Workspace / {{section.label}}</span><h1>{{section.label}}</h1></div><button class="secondary" @click="refresh" :disabled="busy">{{busy?'Refreshing…':'Refresh'}}</button></header>
    <div class="workspace-content" :aria-busy="busy"><p class="workspace-description">{{section.description}}</p>
    <p role="status" class="success" v-if="notice">{{notice}}</p><p role="alert" class="error" v-if="error">{{error}}</p>
    <p v-if="!cap.integration?.ready" class="sr2-integration-status">Credential delivery is not connected yet. You can prepare configurations and journeys; issuance and revocation become available after integration setup.</p>
    <div v-if="tab==='request'" class="card request-card"><h3>Available credentials</h3><p class="empty" v-if="!eligible.length">No credentials are available for your account yet. Your administrator can publish a configuration and grant eligibility.</p><article class="credential-option" v-for="c in eligible" :key="c.id"><h4>{{c.name}}</h4><p>{{c.description}}</p><button @click="start(c.id)" :disabled="busy">Start request</button></article>
      <form v-if="currentStep" @submit.prevent="currentStep.type==='offer'?prepareOffer():next()" class="sr2-journey"><p>Step {{journey.request.step+1}} / {{journey.flow.steps.length}} · version {{journey.request.flowVersion}}</p><h3>{{currentStep.title}}</h3><p class="preserve-lines">{{currentStep.text}}</p><label v-if="currentStep.type==='consent'"><input type="checkbox" v-model="consent" required> I have read and accept this information.</label><label v-for="f in currentStep.fields" :key="f.name">{{f.label}}<input v-model="answers[f.name]" :required="f.required" maxlength="2000"></label><button :disabled="busy">{{currentStep.type==='offer'?'Prepare credential offer':'Continue'}}</button></form>
      <section v-if="offer" aria-live="polite"><p>Offer expires {{new Date(offer.expiresAt).toLocaleString()}}</p><svg v-if="qr" class="offer-qr" :viewBox="'0 0 '+qr.size+' '+qr.size" role="img" aria-label="Credential offer QR code" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/><path :d="qr.path" fill="black"/></svg><p v-else>Open the link below; this offer exceeds QR capacity.</p><a :href="offer.offerUrl" rel="noreferrer">Open credential offer</a></section>
    </div>
    <section v-if="tab==='configurations' && cap.issuer" class="configuration-workspace">
      <div class="workspace-stats"><div class="metric primary"><span class="metric-label">Configurations</span><strong>{{configs.length}}</strong><small>Within your access scope</small></div><div class="metric"><span class="metric-label">Published</span><strong>{{configs.filter(c=>c.activeVersion && c.state!=='archived').length}}</strong><small>Available to eligible members</small></div><div class="metric"><span class="metric-label">Drafts</span><strong>{{configs.filter(c=>c.state==='draft').length}}</strong><small>Prepare before publishing</small></div></div>
      <section class="card registry-card"><div class="registry-toolbar"><div><h3>Credential configurations</h3><p>Manage your organization’s credential catalogue.</p></div><button v-if="cap.globalIssuer" @click="newConfig">+ Create configuration</button></div>
        <div class="registry-filters"><label class="config-search">Search configurations<input type="search" v-model="query" placeholder="Search by name or identifier"></label><label>State<select v-model="configState"><option value="all">All states</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><span class="result-count">{{filteredConfigs.length}} results</span></div>
        <div class="table-wrap"><table><thead><tr><th>Name</th><th>Format</th><th>Status</th><th>Version</th><th>Action</th></tr></thead><tbody><tr v-for="c in filteredConfigs" :key="c.id"><td><strong>{{c.draft.name}}</strong><small>{{c.draft.identifier}}</small></td><td><code>{{c.draft.format}}</code></td><td><span class="badge" :class="'badge-'+c.state">{{c.state}}</span></td><td>{{c.activeVersion?'Published v'+c.activeVersion:'Not published'}}<small>Draft revision {{c.version}}</small></td><td><button class="secondary compact" @click="editConfig(c)">{{c.state==='archived'?'View':'Edit'}}</button></td></tr><tr v-if="!filteredConfigs.length"><td colspan="5" class="empty">{{configs.length?'No configurations match these filters.':'Create your first configuration to get started.'}}</td></tr></tbody></table></div>
      </section>
      <section class="card" v-if="configForm"><h3>{{selected?'Edit configuration':'New configuration'}}</h3><form @submit.prevent="saveConfig" class="sr2-form"><label>Stable identifier<input v-model="configForm.identifier" :disabled="!!selected" required pattern="[A-Za-z][A-Za-z0-9_-]{0,63}"></label><label>Name<input v-model="configForm.name" required maxlength="100"></label><label>Description<textarea v-model="configForm.description" maxlength="1000"></textarea></label><div class="two-column"><label>Protocol profile<select v-model="configForm.profile"><option>oid4vci-draft13</option><option>oid4vci-1.0</option></select></label><label>Credential format<select v-model="configForm.format"><option>jwt_vc_json</option><option v-if="configForm.profile==='oid4vci-draft13'">vc+sd-jwt</option><option v-if="configForm.profile==='oid4vci-1.0'">dc+sd-jwt</option><option>ldp_vc</option></select></label></div><label>Credential types (comma separated)<input :value="configForm.credentialTypes.join(', ')" @input="configForm.credentialTypes=$event.target.value.split(',').map(x=>x.trim()).filter(Boolean)"></label><label v-if="configForm.format.includes('sd-jwt')">VCT<input v-model="configForm.vct" required></label>
      <fieldset><legend>Claim definitions</legend><div v-for="(claim,i) in configForm.claims" :key="i" class="sr2-row"><label>Claim name<input v-model="claim.name" required></label><label>Type<select v-model="claim.type"><option>string</option><option>number</option><option>boolean</option></select></label><label><input type="checkbox" v-model="claim.required">Required</label><button type="button" class="secondary" @click="configForm.claims.splice(i,1)">Remove claim</button></div><button type="button" class="secondary" @click="configForm.claims.push({name:'',type:'string',required:true})">Add claim</button></fieldset>
      <label>Signing mode<select v-model="configForm.signingMode"><option>internal-signing</option><option>participant-signed</option></select></label><label>Tenant key reference<input v-model="configForm.keyRef" required></label><label>Status profile<input v-model="configForm.statusProfile" required></label><label>Approved participant connector<select v-model="configForm.connectorId"><option :value="null">Select an approved connector</option><option v-for="c in availableConnectors" :value="c.id">{{c.draft.name}}</option></select><small>Save the configuration first, then ask a tenant administrator to approve its connector access.</small></label><label>Published journey<select v-model="configForm.flowId"><option :value="null">Assign after creating a journey</option><option v-for="f in flows.filter(x=>x.configurationId===selected?.id && x.activeVersion)" :value="f.id">{{f.draft.name}} · v{{f.activeVersion}}</option></select></label>
      <fieldset><legend>Eligibility</legend><label><input type="checkbox" :checked="configForm.eligibility.roles.includes('principal')" @change="configForm.eligibility.roles=$event.target.checked?['principal']:[]">All enabled tenant principals</label><label>Specific member subject IDs (comma separated)<textarea :value="configForm.eligibility.subjects.join(', ')" @input="configForm.eligibility.subjects=$event.target.value.split(',').map(x=>x.trim()).filter(Boolean)"></textarea></label><label>Requests per minute<input type="number" min="1" max="60" v-model.number="configForm.ratePerMinute"></label><label><input type="checkbox" v-model="configForm.blockReissuance">Block reissuance after revocation</label></fieldset>
      <label>Logo asset<select v-model="configForm.logoAssetId"><option :value="null">No logo</option><option v-for="a in assets.filter(x=>x.configurationId===selected?.id && x.state!=='archived')" :value="a.id">{{a.id}}</option></select></label><label>Background asset<select v-model="configForm.backgroundAssetId"><option :value="null">No background</option><option v-for="a in assets.filter(x=>x.configurationId===selected?.id && x.state!=='archived')" :value="a.id">{{a.id}}</option></select></label><button :disabled="busy || selected?.state==='archived'">Save draft</button></form>
      <div class="actions" v-if="selected && selected.state!=='archived'"><button class="secondary" @click="configAction('validate')">Validate</button><button class="secondary" @click="configAction('preview')">Preview</button><button @click="configAction('publish')">Publish locally</button><button class="danger" @click="configAction('archive')">Archive</button></div>
      <fieldset v-if="selected"><legend>Credential image</legend><label>Use as<select v-model="uploadRole"><option value="logoAssetId">Logo</option><option value="backgroundAssetId">Background</option></select></label><label>Upload PNG (RGB/RGBA, up to 1 MiB and 1024×1024)<input type="file" accept="image/png" @change="uploadScope='configuration';upload($event)"></label></fieldset><ul class="sr2-list"><li v-for="a in assets.filter(x=>x.configurationId===selected?.id)" :key="a.id"><span>{{a.draft.width}}×{{a.draft.height}} · {{a.draft.size}} bytes · {{a.state}}</span><button v-if="!a.public && a.state!=='archived'" class="secondary" @click="archiveAsset(a)">Archive image</button></li></ul><div v-if="selected && selected.state!=='archived'" class="actions"><label>Restore version<input type="number" min="1" v-model="restoreVersion"></label><button class="secondary" @click="restoreConfig">Restore as draft</button></div><p v-if="selected">Active version: {{selected.activeVersion || 'none'}} · Draft revision: {{selected.version}}</p>
      <details v-if="versions.length"><summary>Immutable version history</summary><ol><li v-for="v in versions" :key="v.version">Version {{v.version}} · {{v.content_hash}}</li></ol></details>
      </section></section>
    <section class="card" v-if="tab==='journeys' && cap.issuer"><h3>Credential journeys</h3><button @click="newFlow">Create journey</button><ul class="sr2-list"><li v-for="f in flows" :key="f.id"><button class="secondary" @click="editFlow(f)">{{f.draft.name}} · {{f.state}} · active v{{f.activeVersion || 'none'}}</button></li></ul>
      <form v-if="flowForm" @submit.prevent="flowAction('save')" class="sr2-form"><label>Configuration<select v-model="flowForm.configurationId" :disabled="!!selectedFlow" required><option v-for="c in configs" :value="c.id">{{c.draft.name}}</option></select></label><label>Journey name<input v-model="flowForm.data.name" required maxlength="100"></label><fieldset v-for="(s,i) in flowForm.data.steps" :key="s.id"><legend>Step {{i+1}}</legend><label>Type<select v-model="s.type" @change="s.fields=[]"><option>information</option><option>consent</option><option>input</option><option>confirmation</option><option>status</option><option>offer</option></select></label><label>Heading<input v-model="s.title" required maxlength="100"></label><label>Text<textarea v-model="s.text" maxlength="2000"></textarea></label><template v-if="s.type==='input'"><div v-for="(f,j) in s.fields" :key="j" class="sr2-row"><label>Field name<input v-model="f.name" required></label><label>Label<input v-model="f.label" required></label><label><input type="checkbox" v-model="f.required">Required</label><button type="button" @click="s.fields.splice(j,1)">Remove field</button></div><button type="button" @click="s.fields.push({name:'',label:'',required:true})">Add input field</button></template><div class="actions"><button type="button" class="secondary" @click="moveStep(i,-1)" :disabled="i===0">Move up</button><button type="button" class="secondary" @click="moveStep(i,1)" :disabled="i===flowForm.data.steps.length-1">Move down</button><button type="button" class="secondary" @click="flowForm.data.steps.splice(i,1)">Remove step</button></div></fieldset><button type="button" class="secondary" @click="addStep">Add step</button><button :disabled="busy">Save draft</button></form>
      <div v-if="selectedFlow" class="actions"><button class="secondary" @click="flowAction('preview')">Preview saved draft</button><button @click="flowAction('publish')">Publish journey</button><label>Restore version<input type="number" min="1" v-model="restoreVersion"></label><button class="secondary" @click="flowAction('rollback')">Restore as draft</button></div>
    </section>
    <section class="card" v-if="preview && ['configurations','journeys'].includes(tab)"><h3>Saved draft preview</h3><template v-if="preview.steps"><article v-for="s in preview.steps" :key="s.id"><h4>{{s.title}}</h4><p class="preserve-lines">{{s.text}}</p><p>Step type: {{s.type}}</p><label v-for="f in s.fields">{{f.label}}<input disabled :placeholder="f.required?'Required':'Optional'"></label></article></template><template v-else><h4>{{preview.name}}</h4><p>{{preview.description}}</p><p>{{preview.profile}} · {{preview.format}}</p><ul><li v-for="c in preview.claims">{{c.name}} ({{c.type}}) {{c.required?'required':''}}</li></ul></template><button class="secondary" @click="preview=null">Close preview</button></section>
    <section class="card" v-if="tab==='history' && cap.issuer"><h3>Issuance history</h3><form @submit.prevent="search.cursor='';loadHistory()" class="sr2-form history-filters"><label>Configuration<select v-model="historyConfig" required><option v-for="c in configs" :value="c.id">{{c.draft.name}}</option></select></label><label>Credential ID<input v-model="search.credentialId" placeholder="Exact credential URI"></label><label>Request UUID<input v-model="search.requestId"></label><label>Pseudonymous subject hash<input v-model="search.subjectHash"></label><label>From<input type="datetime-local" v-model="search.from"></label><label>To<input type="datetime-local" v-model="search.to"></label><label>Event type<input v-model="search.type" placeholder="issued, revoked, offered"></label><button :disabled="busy">Search</button></form><div class="table-wrap"><table><thead><tr><th>Time / event</th><th>Credential / request</th><th>Current state</th><th>Status reference</th><th>Subject hash</th><th>Action</th></tr></thead><tbody><tr v-for="e in history" :key="e.cursor"><td>{{new Date(e.createdAt).toLocaleString()}}<small>{{e.type}}</small></td><td><strong>{{e.credentialId || 'Not recorded'}}</strong><small>{{e.requestId || '—'}}</small></td><td><span class="badge" :class="'badge-'+e.currentState">{{e.currentState || '—'}}</span></td><td><template v-if="e.statusReference"><code>{{e.statusReference.id}}</code><small>{{e.statusReference.type}} · {{e.statusReference.statusPurpose}}</small><small v-if="e.statusReference.statusListIndex">Index {{e.statusReference.statusListIndex}}</small></template><span v-else>Not allocated</span></td><td><code>{{e.subjectHash}}</code></td><td><button v-if="e.type==='issued' && e.currentState==='issued'" class="danger" @click="revoke(e.requestId)">Revoke</button></td></tr><tr v-if="!history.length"><td colspan="6" class="empty">Choose a configuration and search to view its history.</td></tr></tbody></table></div><p class="muted">Current state is the latest locally confirmed issuance state. Status references are recorded from issuance, not a live status-list check.</p><button v-if="nextCursor" class="secondary" @click="search.cursor=String(nextCursor);loadHistory(true)">Load older events</button></section>
    <section v-if="tab==='tenant' && cap.tenantAdmin" class="sr2-columns"><section class="card"><h3>Issuer metadata</h3><form @submit.prevent="saveMetadata" class="sr2-form"><label>Protocol profile<select v-model="metadataForm.profile"><option>oid4vci-draft13</option><option>oid4vci-1.0</option></select></label><label>Issuer URL<input v-model="metadataForm.issuer" readonly></label><label>Display name<input v-model="metadataForm.displayName" required></label><label>Authorization server URLs (comma separated)<textarea v-model="authServers" required></textarea></label><label>Tenant DID<input v-model="metadataForm.did" required></label><label>Tenant JWKS URL<input v-model="metadataForm.jwksUrl" type="url" required></label><button :disabled="busy">Save and publish locally</button></form><p>Publication: {{publication?.state?.state || 'draft'}} · desired {{publication?.state?.desired || 0}} / observed {{publication?.state?.observed || 0}}</p><button class="secondary" @click="publishMetadata">Publish to OCM</button></section>
      <section class="card"><h3>Tenant branding</h3><form @submit.prevent="saveSingleton('branding',branding,brandingForm,true)" class="sr2-form"><label>Title<input v-model="brandingForm.title" required></label><label>Description<textarea v-model="brandingForm.description"></textarea></label><label>Accent color<input type="color" v-model="brandingForm.accent"></label><label>Tenant logo PNG<input type="file" accept="image/png" @change="uploadScope='tenant';upload($event)"></label><button :disabled="busy">Activate branding</button></form><h3>Issuance limits</h3><form @submit.prevent="saveSingleton('issuer-settings',settings,settingsForm)" class="sr2-form"><label>Tenant requests per minute<input type="number" min="1" max="120" v-model.number="settingsForm.ratePerMinute"></label><label>Concurrent participant requests<input type="number" min="1" max="8" v-model.number="settingsForm.maxConcurrent"></label><button :disabled="busy">Save limits</button></form><h3>Tenant lifecycle</h3><button class="secondary" @click="lifecycle('suspended')">Suspend tenant</button><button class="danger" @click="lifecycle('deleting')">Request tenant deletion</button></section></section>
    <section class="card" v-if="tab==='connectors' && cap.tenantAdmin"><div class="registry-toolbar"><h3>Participant connectors</h3><button class="secondary" @click="newConnector">+ New connector</button></div><ul class="sr2-list"><li v-for="c in connectors"><button class="secondary" @click="editConnector(c)">{{c.draft.name}} · {{c.id}}</button></li></ul><form @submit.prevent="saveConnector" class="sr2-form"><fieldset><legend>Configuration access</legend><label><input type="checkbox" :checked="connectorForm.configurationIds===null" @change="connectorForm.configurationIds=$event.target.checked?null:[]">Allow all configurations in this tenant</label><template v-if="connectorForm.configurationIds!==null"><label v-for="c in configs.filter(c=>c.state!=='archived')" :key="c.id"><input type="checkbox" :value="c.id" v-model="connectorForm.configurationIds">{{c.draft.name}}</label><p class="muted">No selection denies access. Changes apply immediately to new and in-progress requests.</p></template></fieldset><label>Name<input v-model="connectorForm.name" required></label><label>HTTPS endpoint<input type="url" v-model="connectorForm.endpoint" required></label><label>TLS server name<input v-model="connectorForm.serverName" required></label><label>Protocol version<input v-model="connectorForm.protocolVersion" required></label><label>Client TLS Secret name<input v-model="connectorForm.tlsSecret.name" required></label><label>Trust Secret name<input v-model="connectorForm.trustSecret.name" required></label><label>JWT issuer<input type="url" v-model="connectorForm.jwtIssuer" required></label><label>JWT audience<input v-model="connectorForm.jwtAudience" required></label><label>Scopes (comma separated)<input :value="connectorForm.jwtScopes.join(', ')" @input="connectorForm.jwtScopes=$event.target.value.split(',').map(x=>x.trim()).filter(Boolean)"></label><fieldset><legend>Supported signing modes</legend><label><input type="checkbox" value="internal-signing" v-model="connectorForm.signingModes">Internal signing</label><label><input type="checkbox" value="participant-signed" v-model="connectorForm.signingModes">Participant signed</label></fieldset><label>Deadline (milliseconds)<input type="number" min="100" max="10000" v-model.number="connectorForm.timeoutMs"></label><label>Attempts for verified idempotent calls<input type="number" min="1" max="3" v-model.number="connectorForm.attempts"></label><label>Requests per minute<input type="number" min="1" max="60" v-model.number="connectorForm.ratePerMinute"></label><label>Failures before temporarily pausing calls<input type="number" min="2" max="10" v-model.number="connectorForm.circuitFailureThreshold"></label><label>Pause duration (milliseconds)<input type="number" min="1000" max="300000" v-model.number="connectorForm.circuitCooldownMs"></label><button :disabled="busy">Save and activate connector</button></form></section>
    <slot v-if="tab==='delegation' && cap.tenantAdmin" name="members"></slot>
    <section class="card" v-if="tab==='delegation' && cap.tenantAdmin"><h3>Issuer administration delegation</h3><form @submit.prevent="assign" class="sr2-form"><label>Enabled member<select v-model="grant.subject" required><option v-for="m in members.filter(x=>x.enabled)" :value="m.subject">{{m.username}}</option></select></label><label>Scope<select v-model="grantConfig"><option value="">All configurations, including creation</option><option v-for="c in configs" :value="c.id">{{c.draft.name}}</option></select></label><button :disabled="busy">Assign issuer capability</button></form><ul><li v-for="a in assignments" :key="a.id">{{a.subject}} · {{a.configurationIds===null?'All configurations':a.configurationIds.join(', ')}} · {{a.revoked?'Revoked':'Active'}} <button v-if="!a.revoked" class="secondary" @click="revokeAssignment(a)">Revoke</button></li></ul></section>
    </div></div>
  </section>`
};
